### ISSUE TITLE
How do you install it?

### ISSUE THREAD

**Issue by AshishShanker** [kaushiksanthanam/conan-tools-vs-code#1]
Doesn't seem to be listed on VS Code Extensions and there is no .vsix file either

**Comment by kaushiksanthanam** [comment]
I haven't published it to the vs code extensions store. Will publish it soon and let you know here

**Comment by kaushiksanthanam** [comment]
in the meantime, feel free to download the code, build it locally and install it on your machine
follow the packaging instructions here https://code.visualstudio.com/docs/extensions/publish-extension#_packaging-extensions
also feel free to contribute back

**Comment by Xvdgeest** [comment]
Still ran into some problems, so I'll add what worked for me:
First have the newest npm and nodejs follow:

https://linuxize.com/post/how-to-install-node-js-on-ubuntu-18.04/
Install vsce:
`npm install -g vsce`

clone repo 
`git clone https://github.com/kaushiksanthanam/conan-tools-vs-code.git`

Then in package directory:
`npm install` 

`vsce package`

`code --install-extension conan-tools-0.1.0.vsix`

**Comment by kaushiksanthanam** [comment]
extension is now avlbl in the marketplace. https://marketplace.visualstudio.com/items?itemName=FireBlackHat.conan-tools
