### ISSUE TITLE
Uploading the package to vscode market place

### ISSUE THREAD

**Issue by orshefi** [kaushiksanthanam/conan-tools-vs-code#3]
Hi,

Are you going to uplaod the package to vscode marketplace? If not can I do it on behalf of you?

**Comment by theonlyfoxy** [comment]
@orshefi https://marketplace.visualstudio.com/items?itemName=FireBlackHat.conan-tools

@kaushiksanthanam If you want to extension get removed from marketplace then feel free to ask me.

**Comment by kaushiksanthanam** [comment]
@FIREFOXCYBER thanks for uploading it. 👍
